BootStrap: debootstrap
OSVersion: bionic
MirrorURL: http://archive.ubuntu.com/ubuntu/

%post
    apt-get update
    apt-get upgrade -y
    apt-get install -y python python-setuptools git

    git clone https://github.com/brainvisa/container-demo.git
    cd container-demo
    python setup.py install
    cd ..
    rm -Rf container-demo

    apt-get remove -y git
    apt-get autoremove -y
    apt-get clean
    rm -rf /var/lib/apt/lists/*

%runscript
    exec cdemo_threshold "$@"
